### ISSUE TITLE
Cloud hosting choice

### ISSUE THREAD

**Issue by kopylash** [develar/electron-build-service#3]
Hello!

Just read cloud hosting choice argumentation. Have you seen [Linode](https://www.linode.com/pricing)? 

By my experience, it is as good as DO, but provides twice more RAM. We actually switched from DO to Linode. I understand that doing setups and benchmarking again is not reasonable enough, but maybe my observation may help.

BTW, you are doing great things for electron ecosystem!

**Comment by develar** [comment]
Thanks for issue.

I am aware of Linode and I was a Linode user 5 years ago. 

Linode was great 5 years ago, but not now.

Linode was rejected initially without any benchmarks based on existing reviews and benchmarks. In short, still rejected and nothing changed in the argumentation "why".

Benchmarking is very easy because Docker Swarm is used and the only command is required to setup a new node. 

Of course, if cloud provider is good. Linode is not so good as UpCloud, Vultr, DO because doesn't support cloud-config (user script). But CoreOS image is provided, so, it is easy to setup at least non-production ready node (in terms of security, performance is not affected and benchmarks can be performed).

Results:

* AppImage: 13s 585ms (vs 13s 650ms equals to Vultr).
* AppImage+deb: 92s 583ms (vs 86s 350ms on Vultr).

As you can see, Linode is slower compared to Vultr (deb requires xz compression and does more IO work).

It seems that Linode vCPU nearly equals to Vultr vCPU, but overall system performance is worse.

Even upload/download speed was a little bit worse compared to Vultr despite the fact, that Vultr located in London, and Linode in Frankfurt (much closer to me).

And lack of user-data feature makes Linode not so easy and comfortable. So, not even considered as backup cloud provider in case of Vultr failure (for this role UpCloud is choosen).
